# Site settings
title: Petrafied Ink
description: Tattoo artistry by Petra (they/them) in Fort Wayne, Indiana
author: Petra
baseurl: "" # the subpath of your site
url: "https://petrafied.ink" # the base hostname & protocol
theme: minima

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 9
timezone: "America/Indiana/Indianapolis"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - chrisbobbe_jekyll-theme-prologue.md
  - cotes2020_jekyll-theme-chirpy.md
  - daattali_beautiful-jekyll.md
  - piharpi_jekyll-klise.md
  - site_guide.md
  - filetree.json

# Social media links
social:
  instagram: https://www.instagram.com/shmegl/
  tiktok: https://www.tiktok.com/@shmegl
  facebook: https://www.facebook.com/shmeagl
  venmo: https://account.venmo.com/u/sikorskip
  email: petrafied@thepaintedladyfw.com

# Custom settings
appointment_url: https://tally.so/r/3yYpJ0
shop_name: The Painted Lady
shop_location: Fort Wayne, Indiana
shop_map: https://maps.app.goo.gl/APDiCzUPpAnmppW98
shop_instagram: thepaintedladyfw
important_website: https://cat-bounce.com/

# Sass processing settings
sass:
  style: compressed  # Options: nested, expanded, compact, compressed
  sass_dir: _sass    # Directory containing Sass partials
  load_paths:        # Additional load paths for Sass
    - _sass
    - assets/css
  sourcemap: never   # Options: always, never
